# Compilación y Pruebas Proyecto Java
name: Compilación Java

on:
  # se ejecuta el flujo con cada push y pull request
  # o haciendo clic desde las opciones de Github Actions
  [push, pull_request, workflow_dispatch]
  
jobs:
  build:
  
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java: [ 11, 12, 17 ]

    # se ejecuta en Ubuntu Linux
    runs-on: ${{ matrix.os }}

    # acciones a ejecutar
    steps:
    - name: Descarga el código fuente
      uses: actions/checkout@v2
    
    - name: Configura JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: ${{ matrix.java }}

    - name: Compila el proyecto
      run: mvn -B package --file pom.xml
